### PR TITLE
Dependencies update

### PR DESCRIPTION
**Pull request by chez14**

### CODE REVIEW

**Comment by chez14** [comment]
Will be merged after @repurika has been invited to the repo for access.

**Comment by Namchee** [comment]
@repurika should already have access right now.

**Comment by chez14** [comment]
As this one merged, those dependabots will automatically close the PRs =3=

**Comment by repurika** [comment]
:rocket: PR was released in [`v0.1.0`](https://github.com/Namchee/daily-watori/releases/tag/v0.1.0) :rocket:

**Pull request merged**
